import sys
sys.stdout.reconfigure(encoding="utf-8")
from connection import get_snowflake_connection
import pandas as pd

conn = get_snowflake_connection()

# Full grain comparison: portfolio actual, contract actual, backtest ML, netting
df = pd.read_sql("""
WITH port AS (
    SELECT RENEWAL_MONTH,
        ROUND(SUM(RENEWED_ACTUAL)/SUM(NULLIF(ATR,0))*100, 2) AS PORT_ACTUAL_RATE,
        ROUND(SUM(ATR)/1e6,1) AS PORT_ATR_M
    FROM STREAMLIT_APPS.DBO.V5_SANDBOX_APP_CONTRACT_DETAIL
    WHERE COALESCE(ATR,0) > 0
    GROUP BY 1
),
contract AS (
    SELECT RENEWAL_MONTH,
        ROUND(CONTRACT_RATE_PCT, 2) AS CONTRACT_ACTUAL_RATE,
        ROUND(CONTRACT_ATR/1e6,1) AS CONTRACT_ATR_M
    FROM STREAMLIT_APPS.DBO.V5_SANDBOX_APP_CONTRACT_LVL_MONTHLY
),
bt AS (
    SELECT RENEWAL_MONTH,
        ROUND(SUM(PREDICTED_RETAINED)/SUM(NULLIF(ATR,0))*100, 2) AS BT_PORT_ML_RATE,
        ROUND(SUM(ACTUAL_RETAINED)/SUM(NULLIF(ATR,0))*100, 2) AS BT_PORT_ACTUAL_RATE
    FROM STREAMLIT_APPS.DBO.V5_SANDBOX_APP_BACKTEST
    GROUP BY 1
)
SELECT p.RENEWAL_MONTH,
    p.PORT_ATR_M,
    c.CONTRACT_ATR_M,
    b.BT_PORT_ML_RATE     AS MODEL_PCT_PORTFOLIO,
    p.PORT_ACTUAL_RATE    AS ACTUAL_PCT_PORTFOLIO,
    c.CONTRACT_ACTUAL_RATE AS ACTUAL_PCT_CONTRACT,
    ROUND(c.CONTRACT_ACTUAL_RATE - p.PORT_ACTUAL_RATE, 2) AS NETTING_PP_REALIZED,
    ROUND(b.BT_PORT_ML_RATE - p.PORT_ACTUAL_RATE, 2) AS MODEL_ERROR_PP
FROM port p
JOIN contract c USING (RENEWAL_MONTH)
LEFT JOIN bt b USING (RENEWAL_MONTH)
WHERE p.RENEWAL_MONTH >= '2025-10-01'
ORDER BY 1
""", conn)
print(df.to_string(index=False))
conn.close()
