USE ROLE REACT_APP_ROLE;
USE DATABASE REACT_APP_DB;
USE SCHEMA APP_DATA;
CALL SYSTEM$GET_SERVICE_STATUS('REACT_APP_DB.APP_DATA.REACT_APP_DEMO');
CALL SYSTEM$GET_SERVICE_LOGS('REACT_APP_DB.APP_DATA.REACT_APP_DEMO', '0', 'backend', 200);
