USE ROLE DEVELOPER;

GRANT USAGE ON DATABASE STREAMLIT_APPS TO ROLE REACT_APP_ROLE;
GRANT USAGE ON SCHEMA STREAMLIT_APPS.DBO TO ROLE REACT_APP_ROLE;

GRANT SELECT ON TABLE STREAMLIT_APPS.DBO.V5_SANDBOX_APP_CONTRACT_DETAIL TO ROLE REACT_APP_ROLE;
GRANT SELECT ON TABLE STREAMLIT_APPS.DBO.V5_SANDBOX_APP_BACKTEST TO ROLE REACT_APP_ROLE;
GRANT SELECT ON TABLE STREAMLIT_APPS.DBO.V5_SANDBOX_APP_RUNS TO ROLE REACT_APP_ROLE;
