USE ROLE REACT_APP_ROLE;
USE DATABASE REACT_APP_DB;
USE SCHEMA APP_DATA;

ALTER SERVICE REACT_APP_DEMO RESUME;
CALL SYSTEM$GET_SERVICE_STATUS('REACT_APP_DB.APP_DATA.REACT_APP_DEMO');
SHOW SERVICE CONTAINERS IN SERVICE REACT_APP_DEMO;
SHOW ENDPOINTS IN SERVICE REACT_APP_DEMO;
