USE ROLE REACT_APP_ROLE;
USE DATABASE REACT_APP_DB;
USE SCHEMA APP_DATA;

SHOW COMPUTE POOLS LIKE 'REACT_APP_POOL';
SELECT
  "name",
  "state",
  "min_nodes",
  "max_nodes",
  "instance_family",
  "active_nodes",
  "target_nodes"
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW SERVICES LIKE 'REACT_APP_DEMO%';
SELECT
  "name",
  "status",
  "min_instances",
  "max_instances"
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

CALL SYSTEM$GET_SERVICE_STATUS('REACT_APP_DB.APP_DATA.REACT_APP_DEMO');
SHOW SERVICE CONTAINERS IN SERVICE REACT_APP_DEMO;
SHOW ENDPOINTS IN SERVICE REACT_APP_DEMO;
