USE ROLE STREAMLIT_USER;
USE WAREHOUSE REPORTING_WH;
USE DATABASE STREAMLIT_APPS;
USE SCHEMA DBO;

SET MASTER_TABLE = 'STREAMLIT_APPS.DBO.STAIRCASE_BUSINESS_OUTCOMES_MASTER';

-- 1) Cohort health summary from readiness flags.
WITH base AS (
    SELECT *
    FROM IDENTIFIER($MASTER_TABLE)
)
SELECT
    COUNT(*) AS total_rows,
    COUNT_IF(IS_CHURN_ANALYSIS_READY = 1) AS churn_ready_rows,
    COUNT_IF(IS_RENEWAL_VALUE_ANALYSIS_READY = 1) AS renewal_value_ready_rows,
    COUNT_IF(IS_DOWNSELL_ANALYSIS_READY = 1) AS downsell_ready_rows,
    COUNT_IF(IS_PRODUCT_LOSS_ANALYSIS_READY = 1) AS product_loss_ready_rows
FROM base;

-- 2) Pearson correlation for staircase signals vs business outcomes.
WITH base AS (
    SELECT *
    FROM IDENTIFIER($MASTER_TABLE)
)
SELECT
    'DERIVED_CHURN_FLAG' AS outcome_name,
    'STAIRCASE_HEALTH' AS staircase_metric,
    COUNT(*) AS n_rows,
    CORR(STAIRCASE_HEALTH, DERIVED_CHURN_FLAG) AS pearson_corr
FROM base
WHERE IS_CHURN_ANALYSIS_READY = 1
  AND STAIRCASE_HEALTH IS NOT NULL
  AND DERIVED_CHURN_FLAG IS NOT NULL
UNION ALL
SELECT
    'DERIVED_CHURN_FLAG',
    'STAIRCASE_SENTIMENT',
    COUNT(*),
    CORR(STAIRCASE_SENTIMENT, DERIVED_CHURN_FLAG)
FROM base
WHERE IS_CHURN_ANALYSIS_READY = 1
  AND STAIRCASE_SENTIMENT IS NOT NULL
  AND DERIVED_CHURN_FLAG IS NOT NULL
UNION ALL
SELECT
    'DERIVED_CHURN_FLAG',
    'STAIRCASE_ENGAGEMENT',
    COUNT(*),
    CORR(STAIRCASE_ENGAGEMENT, DERIVED_CHURN_FLAG)
FROM base
WHERE IS_CHURN_ANALYSIS_READY = 1
  AND STAIRCASE_ENGAGEMENT IS NOT NULL
  AND DERIVED_CHURN_FLAG IS NOT NULL
UNION ALL
SELECT
    'RENEWAL_VALUE',
    'STAIRCASE_HEALTH',
    COUNT(*),
    CORR(STAIRCASE_HEALTH, ALLOCATED_CARR_RENEW_GROSS_C_BUDGET_RATE)
FROM base
WHERE IS_RENEWAL_VALUE_ANALYSIS_READY = 1
  AND STAIRCASE_HEALTH IS NOT NULL
  AND ALLOCATED_CARR_RENEW_GROSS_C_BUDGET_RATE IS NOT NULL
UNION ALL
SELECT
    'RENEWAL_VALUE',
    'STAIRCASE_SENTIMENT',
    COUNT(*),
    CORR(STAIRCASE_SENTIMENT, ALLOCATED_CARR_RENEW_GROSS_C_BUDGET_RATE)
FROM base
WHERE IS_RENEWAL_VALUE_ANALYSIS_READY = 1
  AND STAIRCASE_SENTIMENT IS NOT NULL
  AND ALLOCATED_CARR_RENEW_GROSS_C_BUDGET_RATE IS NOT NULL
UNION ALL
SELECT
    'RENEWAL_VALUE',
    'STAIRCASE_ENGAGEMENT',
    COUNT(*),
    CORR(STAIRCASE_ENGAGEMENT, ALLOCATED_CARR_RENEW_GROSS_C_BUDGET_RATE)
FROM base
WHERE IS_RENEWAL_VALUE_ANALYSIS_READY = 1
  AND STAIRCASE_ENGAGEMENT IS NOT NULL
  AND ALLOCATED_CARR_RENEW_GROSS_C_BUDGET_RATE IS NOT NULL
UNION ALL
SELECT
    'DOWNSELL_VALUE',
    'STAIRCASE_HEALTH',
    COUNT(*),
    CORR(STAIRCASE_HEALTH, DOWNGRADE_DOLLARS_C_BUDGET_RATE)
FROM base
WHERE IS_DOWNSELL_ANALYSIS_READY = 1
  AND STAIRCASE_HEALTH IS NOT NULL
  AND DOWNGRADE_DOLLARS_C_BUDGET_RATE IS NOT NULL
UNION ALL
SELECT
    'DOWNSELL_VALUE',
    'STAIRCASE_SENTIMENT',
    COUNT(*),
    CORR(STAIRCASE_SENTIMENT, DOWNGRADE_DOLLARS_C_BUDGET_RATE)
FROM base
WHERE IS_DOWNSELL_ANALYSIS_READY = 1
  AND STAIRCASE_SENTIMENT IS NOT NULL
  AND DOWNGRADE_DOLLARS_C_BUDGET_RATE IS NOT NULL
UNION ALL
SELECT
    'DOWNSELL_VALUE',
    'STAIRCASE_ENGAGEMENT',
    COUNT(*),
    CORR(STAIRCASE_ENGAGEMENT, DOWNGRADE_DOLLARS_C_BUDGET_RATE)
FROM base
WHERE IS_DOWNSELL_ANALYSIS_READY = 1
  AND STAIRCASE_ENGAGEMENT IS NOT NULL
  AND DOWNGRADE_DOLLARS_C_BUDGET_RATE IS NOT NULL
UNION ALL
SELECT
    'PRODUCT_LOSS_VALUE',
    'STAIRCASE_HEALTH',
    COUNT(*),
    CORR(STAIRCASE_HEALTH, LOST_OR_CHURN_DOLLARS_C_BUDGET_RATE)
FROM base
WHERE IS_PRODUCT_LOSS_ANALYSIS_READY = 1
  AND STAIRCASE_HEALTH IS NOT NULL
  AND LOST_OR_CHURN_DOLLARS_C_BUDGET_RATE IS NOT NULL
UNION ALL
SELECT
    'PRODUCT_LOSS_VALUE',
    'STAIRCASE_SENTIMENT',
    COUNT(*),
    CORR(STAIRCASE_SENTIMENT, LOST_OR_CHURN_DOLLARS_C_BUDGET_RATE)
FROM base
WHERE IS_PRODUCT_LOSS_ANALYSIS_READY = 1
  AND STAIRCASE_SENTIMENT IS NOT NULL
  AND LOST_OR_CHURN_DOLLARS_C_BUDGET_RATE IS NOT NULL
UNION ALL
SELECT
    'PRODUCT_LOSS_VALUE',
    'STAIRCASE_ENGAGEMENT',
    COUNT(*),
    CORR(STAIRCASE_ENGAGEMENT, LOST_OR_CHURN_DOLLARS_C_BUDGET_RATE)
FROM base
WHERE IS_PRODUCT_LOSS_ANALYSIS_READY = 1
  AND STAIRCASE_ENGAGEMENT IS NOT NULL
  AND LOST_OR_CHURN_DOLLARS_C_BUDGET_RATE IS NOT NULL
ORDER BY outcome_name, staircase_metric;

-- 3) Spearman correlation for staircase signals vs derived churn.
WITH base AS (
    SELECT *
    FROM IDENTIFIER($MASTER_TABLE)
),
health AS (
    SELECT
        RANK() OVER (ORDER BY STAIRCASE_HEALTH) AS rx,
        RANK() OVER (ORDER BY DERIVED_CHURN_FLAG) AS ry
    FROM base
    WHERE IS_CHURN_ANALYSIS_READY = 1
      AND STAIRCASE_HEALTH IS NOT NULL
      AND DERIVED_CHURN_FLAG IS NOT NULL
),
sentiment AS (
    SELECT
        RANK() OVER (ORDER BY STAIRCASE_SENTIMENT) AS rx,
        RANK() OVER (ORDER BY DERIVED_CHURN_FLAG) AS ry
    FROM base
    WHERE IS_CHURN_ANALYSIS_READY = 1
      AND STAIRCASE_SENTIMENT IS NOT NULL
      AND DERIVED_CHURN_FLAG IS NOT NULL
),
engagement AS (
    SELECT
        RANK() OVER (ORDER BY STAIRCASE_ENGAGEMENT) AS rx,
        RANK() OVER (ORDER BY DERIVED_CHURN_FLAG) AS ry
    FROM base
    WHERE IS_CHURN_ANALYSIS_READY = 1
      AND STAIRCASE_ENGAGEMENT IS NOT NULL
      AND DERIVED_CHURN_FLAG IS NOT NULL
)
SELECT
    'DERIVED_CHURN_FLAG' AS outcome_name,
    'STAIRCASE_HEALTH' AS staircase_metric,
    (SELECT COUNT(*) FROM health) AS n_rows,
    (SELECT CORR(rx, ry) FROM health) AS spearman_corr
UNION ALL
SELECT
    'DERIVED_CHURN_FLAG',
    'STAIRCASE_SENTIMENT',
    (SELECT COUNT(*) FROM sentiment),
    (SELECT CORR(rx, ry) FROM sentiment)
UNION ALL
SELECT
    'DERIVED_CHURN_FLAG',
    'STAIRCASE_ENGAGEMENT',
    (SELECT COUNT(*) FROM engagement),
    (SELECT CORR(rx, ry) FROM engagement)
ORDER BY staircase_metric;

-- 4) Quintile lift for staircase vs churn rate.
WITH base AS (
    SELECT *
    FROM IDENTIFIER($MASTER_TABLE)
),
feature_rows AS (
    SELECT
        'STAIRCASE_HEALTH' AS staircase_metric,
        STAIRCASE_HEALTH AS staircase_value,
        DERIVED_CHURN_FLAG
    FROM base
    WHERE IS_CHURN_ANALYSIS_READY = 1
      AND STAIRCASE_HEALTH IS NOT NULL
      AND DERIVED_CHURN_FLAG IS NOT NULL

    UNION ALL

    SELECT
        'STAIRCASE_SENTIMENT',
        STAIRCASE_SENTIMENT,
        DERIVED_CHURN_FLAG
    FROM base
    WHERE IS_CHURN_ANALYSIS_READY = 1
      AND STAIRCASE_SENTIMENT IS NOT NULL
      AND DERIVED_CHURN_FLAG IS NOT NULL

    UNION ALL

    SELECT
        'STAIRCASE_ENGAGEMENT',
        STAIRCASE_ENGAGEMENT,
        DERIVED_CHURN_FLAG
    FROM base
    WHERE IS_CHURN_ANALYSIS_READY = 1
      AND STAIRCASE_ENGAGEMENT IS NOT NULL
      AND DERIVED_CHURN_FLAG IS NOT NULL
),
scored AS (
    SELECT
        staircase_metric,
        staircase_value,
        DERIVED_CHURN_FLAG,
        NTILE(5) OVER (PARTITION BY staircase_metric ORDER BY staircase_value) AS staircase_quintile
    FROM feature_rows
)
SELECT
    staircase_metric,
    staircase_quintile,
    COUNT(*) AS n_rows,
    MIN(staircase_value) AS min_score,
    MAX(staircase_value) AS max_score,
    AVG(DERIVED_CHURN_FLAG) AS churn_rate
FROM scored
GROUP BY 1, 2
ORDER BY staircase_metric, staircase_quintile;

-- 5) Quintile lift for staircase vs value outcomes.
WITH base AS (
    SELECT *
    FROM IDENTIFIER($MASTER_TABLE)
),
value_rows AS (
    SELECT
        'RENEWAL_VALUE' AS outcome_name,
        'STAIRCASE_HEALTH' AS staircase_metric,
        STAIRCASE_HEALTH AS staircase_value,
        ALLOCATED_CARR_RENEW_GROSS_C_BUDGET_RATE AS outcome_value
    FROM base
    WHERE IS_RENEWAL_VALUE_ANALYSIS_READY = 1
      AND STAIRCASE_HEALTH IS NOT NULL
      AND ALLOCATED_CARR_RENEW_GROSS_C_BUDGET_RATE IS NOT NULL

    UNION ALL

    SELECT
        'RENEWAL_VALUE',
        'STAIRCASE_SENTIMENT',
        STAIRCASE_SENTIMENT,
        ALLOCATED_CARR_RENEW_GROSS_C_BUDGET_RATE
    FROM base
    WHERE IS_RENEWAL_VALUE_ANALYSIS_READY = 1
      AND STAIRCASE_SENTIMENT IS NOT NULL
      AND ALLOCATED_CARR_RENEW_GROSS_C_BUDGET_RATE IS NOT NULL

    UNION ALL

    SELECT
        'RENEWAL_VALUE',
        'STAIRCASE_ENGAGEMENT',
        STAIRCASE_ENGAGEMENT,
        ALLOCATED_CARR_RENEW_GROSS_C_BUDGET_RATE
    FROM base
    WHERE IS_RENEWAL_VALUE_ANALYSIS_READY = 1
      AND STAIRCASE_ENGAGEMENT IS NOT NULL
      AND ALLOCATED_CARR_RENEW_GROSS_C_BUDGET_RATE IS NOT NULL

    UNION ALL

    SELECT
        'DOWNSELL_VALUE',
        'STAIRCASE_HEALTH',
        STAIRCASE_HEALTH,
        DOWNGRADE_DOLLARS_C_BUDGET_RATE
    FROM base
    WHERE IS_DOWNSELL_ANALYSIS_READY = 1
      AND STAIRCASE_HEALTH IS NOT NULL
      AND DOWNGRADE_DOLLARS_C_BUDGET_RATE IS NOT NULL

    UNION ALL

    SELECT
        'DOWNSELL_VALUE',
        'STAIRCASE_SENTIMENT',
        STAIRCASE_SENTIMENT,
        DOWNGRADE_DOLLARS_C_BUDGET_RATE
    FROM base
    WHERE IS_DOWNSELL_ANALYSIS_READY = 1
      AND STAIRCASE_SENTIMENT IS NOT NULL
      AND DOWNGRADE_DOLLARS_C_BUDGET_RATE IS NOT NULL

    UNION ALL

    SELECT
        'DOWNSELL_VALUE',
        'STAIRCASE_ENGAGEMENT',
        STAIRCASE_ENGAGEMENT,
        DOWNGRADE_DOLLARS_C_BUDGET_RATE
    FROM base
    WHERE IS_DOWNSELL_ANALYSIS_READY = 1
      AND STAIRCASE_ENGAGEMENT IS NOT NULL
      AND DOWNGRADE_DOLLARS_C_BUDGET_RATE IS NOT NULL

    UNION ALL

    SELECT
        'PRODUCT_LOSS_VALUE',
        'STAIRCASE_HEALTH',
        STAIRCASE_HEALTH,
        LOST_OR_CHURN_DOLLARS_C_BUDGET_RATE
    FROM base
    WHERE IS_PRODUCT_LOSS_ANALYSIS_READY = 1
      AND STAIRCASE_HEALTH IS NOT NULL
      AND LOST_OR_CHURN_DOLLARS_C_BUDGET_RATE IS NOT NULL

    UNION ALL

    SELECT
        'PRODUCT_LOSS_VALUE',
        'STAIRCASE_SENTIMENT',
        STAIRCASE_SENTIMENT,
        LOST_OR_CHURN_DOLLARS_C_BUDGET_RATE
    FROM base
    WHERE IS_PRODUCT_LOSS_ANALYSIS_READY = 1
      AND STAIRCASE_SENTIMENT IS NOT NULL
      AND LOST_OR_CHURN_DOLLARS_C_BUDGET_RATE IS NOT NULL

    UNION ALL

    SELECT
        'PRODUCT_LOSS_VALUE',
        'STAIRCASE_ENGAGEMENT',
        STAIRCASE_ENGAGEMENT,
        LOST_OR_CHURN_DOLLARS_C_BUDGET_RATE
    FROM base
    WHERE IS_PRODUCT_LOSS_ANALYSIS_READY = 1
      AND STAIRCASE_ENGAGEMENT IS NOT NULL
      AND LOST_OR_CHURN_DOLLARS_C_BUDGET_RATE IS NOT NULL
),
scored AS (
    SELECT
        outcome_name,
        staircase_metric,
        staircase_value,
        outcome_value,
        NTILE(5) OVER (PARTITION BY outcome_name, staircase_metric ORDER BY staircase_value) AS staircase_quintile
    FROM value_rows
)
SELECT
    outcome_name,
    staircase_metric,
    staircase_quintile,
    COUNT(*) AS n_rows,
    MIN(staircase_value) AS min_score,
    MAX(staircase_value) AS max_score,
    AVG(outcome_value) AS avg_outcome_value,
    MEDIAN(outcome_value) AS median_outcome_value
FROM scored
GROUP BY 1, 2, 3
ORDER BY outcome_name, staircase_metric, staircase_quintile;
