-- =============================================================================
-- Vendor-specific USAGE views (shim layer)
-- Vendor recon SQLs reference per-vendor <VENDOR>_USAGE tables.
-- These are now sourced from THIRD_PARTY_RECON_VENDOR_USAGE_PROD.
-- =============================================================================
USE ROLE DEVELOPER;
USE WAREHOUSE REPORTING_WH;
USE DATABASE ANALYTICS_DEV;
USE SCHEMA DBT_NFOLD_TRANSFORMATION;

CREATE OR REPLACE VIEW ACRONIS_USAGE AS
SELECT BILLING_MONTH, VENDOR_PARTNER_NAME, VENDOR_PRODUCT_SKU, MODIFIER,
       QUANTITY, UNIT_PRICE, AMOUNT, CURRENCY
FROM THIRD_PARTY_RECON_VENDOR_USAGE_PROD WHERE VENDOR = 'Acronis';

CREATE OR REPLACE VIEW AUVIK_USAGE AS
SELECT BILLING_MONTH, VENDOR_PARTNER_NAME, VENDOR_PRODUCT_SKU, MODIFIER,
       QUANTITY, UNIT_PRICE, AMOUNT, CURRENCY
FROM THIRD_PARTY_RECON_VENDOR_USAGE_PROD WHERE VENDOR = 'Auvik';

CREATE OR REPLACE VIEW BITDEFENDER_USAGE AS
SELECT BILLING_MONTH, VENDOR_PARTNER_NAME, VENDOR_PRODUCT_SKU, MODIFIER,
       QUANTITY, UNIT_PRICE, AMOUNT, CURRENCY
FROM THIRD_PARTY_RECON_VENDOR_USAGE_PROD WHERE VENDOR = 'Bitdefender';

CREATE OR REPLACE VIEW ESET_USAGE AS
SELECT BILLING_MONTH, VENDOR_PARTNER_NAME, VENDOR_PRODUCT_SKU, MODIFIER,
       QUANTITY, UNIT_PRICE, AMOUNT, CURRENCY
FROM THIRD_PARTY_RECON_VENDOR_USAGE_PROD WHERE VENDOR = 'ESET';

CREATE OR REPLACE VIEW EXIUM_USAGE AS
SELECT BILLING_MONTH, VENDOR_PARTNER_NAME, VENDOR_PRODUCT_SKU, MODIFIER,
       QUANTITY, UNIT_PRICE, AMOUNT, CURRENCY
FROM THIRD_PARTY_RECON_VENDOR_USAGE_PROD WHERE VENDOR = 'Exium';

CREATE OR REPLACE VIEW KEEPIT_USAGE AS
SELECT BILLING_MONTH, VENDOR_PARTNER_NAME, VENDOR_PRODUCT_SKU, MODIFIER,
       QUANTITY, UNIT_PRICE, AMOUNT, CURRENCY
FROM THIRD_PARTY_RECON_VENDOR_USAGE_PROD WHERE VENDOR = 'KeepIT';

CREATE OR REPLACE VIEW PROOFPOINT_USAGE AS
SELECT BILLING_MONTH, VENDOR_PARTNER_NAME, VENDOR_PRODUCT_SKU, MODIFIER,
       QUANTITY, UNIT_PRICE, AMOUNT, CURRENCY
FROM THIRD_PARTY_RECON_VENDOR_USAGE_PROD WHERE VENDOR = 'Proofpoint';

CREATE OR REPLACE VIEW SENTINELONE_USAGE AS
SELECT BILLING_MONTH, VENDOR_PARTNER_NAME, VENDOR_PRODUCT_SKU, MODIFIER,
       QUANTITY, UNIT_PRICE, AMOUNT, CURRENCY
FROM THIRD_PARTY_RECON_VENDOR_USAGE_PROD WHERE VENDOR = 'SentinelOne';

CREATE OR REPLACE VIEW WEBROOT_USAGE AS
SELECT BILLING_MONTH, VENDOR_PARTNER_NAME, VENDOR_PRODUCT_SKU, MODIFIER,
       QUANTITY, UNIT_PRICE, AMOUNT, CURRENCY
FROM THIRD_PARTY_RECON_VENDOR_USAGE_PROD WHERE VENDOR = 'Webroot';
