from connection import fetch_dataframe
q = "SELECT COLUMN_NAME FROM STREAMLIT_APPS.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='V5_SANDBOX_APP_CONTRACT_DETAIL' ORDER BY ORDINAL_POSITION"
df = fetch_dataframe(q)
print(df["COLUMN_NAME"].tolist())
