-- =============================================================================
-- 02_unified_reference_maps.sql
--
-- Purpose: replace 9 per-vendor partner-mapping tables + 7 per-vendor sku-map
-- tables with a single unified pair, plus backward-compatible views so the
-- 9 vendor Reconciliation_Script_Prod.sql files continue to work unchanged.
--
-- After this runs:
--   Physical:
--     RECON_PARTNER_MAP        (VENDOR, PARTNER_NAME, PARENT_COMPANY,
--                               SF_ID, CMS_ID, ZUORA_NAME)  DISTINCT rows
--     RECON_SKU_MAP            (VENDOR, VENDOR_PRODUCT, VENDOR_SKU, CW_SKU,
--                               SKU_MATCH_KEY, MAPPING_NOTES,
--                               CONTRACT_COST_RATE, CW_RETAIL_RATE)  DISTINCT rows
--   Views (backward-compat, one per vendor -- consumed by vendor SQLs):
--     <VENDOR>_PARTNER_MAPPING_V5  -> SELECT * FROM RECON_PARTNER_MAP WHERE VENDOR = '<v>'
--     <VENDOR>_SKU_MAP_V5          -> SELECT * FROM RECON_SKU_MAP     WHERE VENDOR = '<v>'
--
--   The pre-existing physical tables are renamed to
--     <VENDOR>_PARTNER_MAPPING_V5_LEGACY_20260823
--     <VENDOR>_SKU_MAP_V5_LEGACY_20260823
--   as a safety net. Drop them once we're confident.
-- =============================================================================

USE ROLE DEVELOPER;
USE WAREHOUSE REPORTING_WH;
USE DATABASE ANALYTICS_DEV;
USE SCHEMA DBT_NFOLD_TRANSFORMATION;

-- -----------------------------------------------------------------------------
-- 1) PARTNER map: union all 8 existing seeds, DISTINCT dedup on all 6 cols.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE TABLE RECON_PARTNER_MAP AS
SELECT DISTINCT
    VENDOR::VARCHAR         AS VENDOR,
    PARTNER_NAME::VARCHAR   AS PARTNER_NAME,
    PARENT_COMPANY::VARCHAR AS PARENT_COMPANY,
    SF_ID::VARCHAR          AS SF_ID,
    CMS_ID::VARCHAR         AS CMS_ID,
    ZUORA_NAME::VARCHAR     AS ZUORA_NAME
FROM (
    SELECT * FROM ACRONIS_PARTNER_MAPPING_V5
    UNION ALL SELECT * FROM AUVIK_PARTNER_MAPPING_V5
    UNION ALL SELECT * FROM BITDEFENDER_PARTNER_MAPPING_V5
    UNION ALL SELECT * FROM ESET_PARTNER_MAPPING_V5
    UNION ALL SELECT * FROM KEEPIT_PARTNER_MAPPING_V5
    UNION ALL SELECT * FROM PROOFPOINT_PARTNER_MAPPING_V5
    UNION ALL SELECT * FROM SENTINELONE_PARTNER_MAPPING_V5
    UNION ALL SELECT * FROM WEBROOT_PARTNER_MAPPING_V5
);

-- -----------------------------------------------------------------------------
-- 2) SKU map: union all 7 existing seeds, DISTINCT dedup on all 8 cols.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE TABLE RECON_SKU_MAP AS
SELECT DISTINCT
    VENDOR::VARCHAR             AS VENDOR,
    VENDOR_PRODUCT::VARCHAR     AS VENDOR_PRODUCT,
    VENDOR_SKU::VARCHAR         AS VENDOR_SKU,
    CW_SKU::VARCHAR             AS CW_SKU,
    SKU_MATCH_KEY::VARCHAR      AS SKU_MATCH_KEY,
    MAPPING_NOTES::VARCHAR      AS MAPPING_NOTES,
    CONTRACT_COST_RATE::FLOAT   AS CONTRACT_COST_RATE,
    CW_RETAIL_RATE::FLOAT       AS CW_RETAIL_RATE
FROM (
    SELECT * FROM ACRONIS_SKU_MAP_V5
    UNION ALL SELECT * FROM AUVIK_SKU_MAP_V5
    UNION ALL SELECT * FROM BITDEFENDER_SKU_MAP_V5
    UNION ALL SELECT * FROM ESET_SKU_MAP_V5
    UNION ALL SELECT * FROM KEEPIT_SKU_MAP_V5
    UNION ALL SELECT * FROM PROOFPOINT_SKU_MAP_V5
    UNION ALL SELECT * FROM WEBROOT_SKU_MAP_V5
);

-- -----------------------------------------------------------------------------
-- 3) Rename existing physical seeds to _LEGACY_20260823. Safety net.
--    (Exium partner + Exium/SentinelOne sku were never present, so no rename.)
-- -----------------------------------------------------------------------------
ALTER TABLE ACRONIS_PARTNER_MAPPING_V5     RENAME TO ACRONIS_PARTNER_MAPPING_V5_LEGACY_20260823;
ALTER TABLE AUVIK_PARTNER_MAPPING_V5       RENAME TO AUVIK_PARTNER_MAPPING_V5_LEGACY_20260823;
ALTER TABLE BITDEFENDER_PARTNER_MAPPING_V5 RENAME TO BITDEFENDER_PARTNER_MAPPING_V5_LEGACY_20260823;
ALTER TABLE ESET_PARTNER_MAPPING_V5        RENAME TO ESET_PARTNER_MAPPING_V5_LEGACY_20260823;
ALTER TABLE KEEPIT_PARTNER_MAPPING_V5      RENAME TO KEEPIT_PARTNER_MAPPING_V5_LEGACY_20260823;
ALTER TABLE PROOFPOINT_PARTNER_MAPPING_V5  RENAME TO PROOFPOINT_PARTNER_MAPPING_V5_LEGACY_20260823;
ALTER TABLE SENTINELONE_PARTNER_MAPPING_V5 RENAME TO SENTINELONE_PARTNER_MAPPING_V5_LEGACY_20260823;
ALTER TABLE WEBROOT_PARTNER_MAPPING_V5     RENAME TO WEBROOT_PARTNER_MAPPING_V5_LEGACY_20260823;

ALTER TABLE ACRONIS_SKU_MAP_V5     RENAME TO ACRONIS_SKU_MAP_V5_LEGACY_20260823;
ALTER TABLE AUVIK_SKU_MAP_V5       RENAME TO AUVIK_SKU_MAP_V5_LEGACY_20260823;
ALTER TABLE BITDEFENDER_SKU_MAP_V5 RENAME TO BITDEFENDER_SKU_MAP_V5_LEGACY_20260823;
ALTER TABLE ESET_SKU_MAP_V5        RENAME TO ESET_SKU_MAP_V5_LEGACY_20260823;
ALTER TABLE KEEPIT_SKU_MAP_V5      RENAME TO KEEPIT_SKU_MAP_V5_LEGACY_20260823;
ALTER TABLE PROOFPOINT_SKU_MAP_V5  RENAME TO PROOFPOINT_SKU_MAP_V5_LEGACY_20260823;
ALTER TABLE WEBROOT_SKU_MAP_V5     RENAME TO WEBROOT_SKU_MAP_V5_LEGACY_20260823;

-- -----------------------------------------------------------------------------
-- 4) Create backward-compat views with the ORIGINAL names, so the 9 vendor
--    Reconciliation_Script_Prod.sql files continue to work with zero edits.
--    Views for Exium (partner + sku) and SentinelOne (sku) also created so
--    those vendor SQLs no longer crash on missing objects -- they just get
--    filtered to zero rows until real map data is added.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW ACRONIS_PARTNER_MAPPING_V5     AS SELECT * FROM RECON_PARTNER_MAP WHERE VENDOR = 'Acronis';
CREATE OR REPLACE VIEW AUVIK_PARTNER_MAPPING_V5       AS SELECT * FROM RECON_PARTNER_MAP WHERE VENDOR = 'Auvik';
CREATE OR REPLACE VIEW BITDEFENDER_PARTNER_MAPPING_V5 AS SELECT * FROM RECON_PARTNER_MAP WHERE VENDOR = 'Bitdefender';
CREATE OR REPLACE VIEW ESET_PARTNER_MAPPING_V5        AS SELECT * FROM RECON_PARTNER_MAP WHERE VENDOR = 'ESET';
CREATE OR REPLACE VIEW EXIUM_PARTNER_MAPPING_V5       AS SELECT * FROM RECON_PARTNER_MAP WHERE VENDOR = 'Exium';
CREATE OR REPLACE VIEW KEEPIT_PARTNER_MAPPING_V5      AS SELECT * FROM RECON_PARTNER_MAP WHERE VENDOR = 'KeepIT';
CREATE OR REPLACE VIEW PROOFPOINT_PARTNER_MAPPING_V5  AS SELECT * FROM RECON_PARTNER_MAP WHERE VENDOR = 'Proofpoint';
CREATE OR REPLACE VIEW SENTINELONE_PARTNER_MAPPING_V5 AS SELECT * FROM RECON_PARTNER_MAP WHERE VENDOR = 'SentinelOne';
CREATE OR REPLACE VIEW WEBROOT_PARTNER_MAPPING_V5     AS SELECT * FROM RECON_PARTNER_MAP WHERE VENDOR = 'Webroot';

CREATE OR REPLACE VIEW ACRONIS_SKU_MAP_V5     AS SELECT * FROM RECON_SKU_MAP WHERE VENDOR = 'Acronis';
CREATE OR REPLACE VIEW AUVIK_SKU_MAP_V5       AS SELECT * FROM RECON_SKU_MAP WHERE VENDOR = 'Auvik';
CREATE OR REPLACE VIEW BITDEFENDER_SKU_MAP_V5 AS SELECT * FROM RECON_SKU_MAP WHERE VENDOR = 'Bitdefender';
CREATE OR REPLACE VIEW ESET_SKU_MAP_V5        AS SELECT * FROM RECON_SKU_MAP WHERE VENDOR = 'ESET';
CREATE OR REPLACE VIEW EXIUM_SKU_MAP_V5       AS SELECT * FROM RECON_SKU_MAP WHERE VENDOR = 'Exium';
CREATE OR REPLACE VIEW KEEPIT_SKU_MAP_V5      AS SELECT * FROM RECON_SKU_MAP WHERE VENDOR = 'KeepIT';
CREATE OR REPLACE VIEW PROOFPOINT_SKU_MAP_V5  AS SELECT * FROM RECON_SKU_MAP WHERE VENDOR = 'Proofpoint';
CREATE OR REPLACE VIEW SENTINELONE_SKU_MAP_V5 AS SELECT * FROM RECON_SKU_MAP WHERE VENDOR = 'SentinelOne';
CREATE OR REPLACE VIEW WEBROOT_SKU_MAP_V5     AS SELECT * FROM RECON_SKU_MAP WHERE VENDOR = 'Webroot';
